# Generated by Django 6.0 on 2026-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_topic_category_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upc_code',
            field=models.CharField(blank=True, db_index=True, help_text='Universal Product Code (UPC/EAN barcode number)', max_length=20, null=True, unique=True),
        ),
    ]
